### Import Libaries

In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv(r'C:\users\anik\desktop\data.csv')

In [36]:
df

,cost,Normalization manually,Standardization,Robust Scaler,Max Absolute Scaler
0,110,0.2,-0.41,0.043,0.73
1,105,0.1,-0.74,0.000,0.70
2,115,0.3,-0.07,0.956,0.76
3,120,0.4,0.26,1.000,0.80
4,110,0.2,-0.41,0.043,0.73
5,130,0.6,0.92,0.220,0.86
6,150,1.0,2.25,1.260,1.00
7,100,0.0,-1.07,-0.043,0.67
8,105,0.1,-0.74,0.000,0.70

In [37]:
print(df.dtypes)

cost                        int64
Normalization manually    float64
Standardization           float64
Robust Scaler             float64
Max Absolute Scaler       float64
dtype: object

### Normalization

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
scaler = MinMaxScaler()

In [40]:
df['normalization_function'] = scaler.fit_transform(df[['cost']])

In [41]:
df

,cost,Normalization manually,Standardization,Robust Scaler,Max Absolute Scaler,normalization_function
0,110,0.2,-0.41,0.043,0.73,0.2
1,105,0.1,-0.74,0.000,0.70,0.1
2,115,0.3,-0.07,0.956,0.76,0.3
3,120,0.4,0.26,1.000,0.80,0.4
4,110,0.2,-0.41,0.043,0.73,0.2
5,130,0.6,0.92,0.220,0.86,0.6
6,150,1.0,2.25,1.260,1.00,1.0
7,100,0.0,-1.07,-0.043,0.67,0.0
8,105,0.1,-0.74,0.000,0.70,0.1

### Standard scaler function

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
std = StandardScaler()

In [44]:
df['Standardization_function'] = std.fit_transform(df[['cost']])
df

,cost,Normalization manually,Standardization,Robust Scaler,Max Absolute Scaler,normalization_function,Standardization_function
0,110,0.2,-0.41,0.043,0.73,0.2,-0.416356
1,105,0.1,-0.74,0.000,0.70,0.1,-0.757011
2,115,0.3,-0.07,0.956,0.76,0.3,-0.075701
3,120,0.4,0.26,1.000,0.80,0.4,0.264954
4,110,0.2,-0.41,0.043,0.73,0.2,-0.416356
5,130,0.6,0.92,0.220,0.86,0.6,0.946264
6,150,1.0,2.25,1.260,1.00,1.0,2.308884
7,100,0.0,-1.07,-0.043,0.67,0.0,-1.097666
8,105,0.1,-0.74,0.000,0.70,0.1,-0.757011

### RobustScaler_function

In [45]:
from sklearn.preprocessing import RobustScaler

In [46]:
df['RobustScaler_function'] = RobustScaler().fit_transform(df[['cost']])
df

,cost,Normalization manually,Standardization,Robust Scaler,Max Absolute Scaler,normalization_function,Standardization_function,RobustScaler_function
0,110,0.2,-0.41,0.043,0.73,0.2,-0.416356,0.000000
1,105,0.1,-0.74,0.000,0.70,0.1,-0.757011,-0.333333
2,115,0.3,-0.07,0.956,0.76,0.3,-0.075701,0.333333
3,120,0.4,0.26,1.000,0.80,0.4,0.264954,0.666667
4,110,0.2,-0.41,0.043,0.73,0.2,-0.416356,0.000000
5,130,0.6,0.92,0.220,0.86,0.6,0.946264,1.333333
6,150,1.0,2.25,1.260,1.00,1.0,2.308884,2.666667
7,100,0.0,-1.07,-0.043,0.67,0.0,-1.097666,-0.666667
8,105,0.1,-0.74,0.000,0.70,0.1,-0.757011,-0.333333

### Max abs

In [47]:
from sklearn.preprocessing import MaxAbsScaler

In [48]:
scaler = MaxAbsScaler()
df['scaler_abs_function'] = scaler.fit_transform(df[['cost']])
df

,cost,Normalization manually,Standardization,Robust Scaler,Max Absolute Scaler,normalization_function,Standardization_function,RobustScaler_function,scaler_abs_function
0,110,0.2,-0.41,0.043,0.73,0.2,-0.416356,0.000000,0.733333
1,105,0.1,-0.74,0.000,0.70,0.1,-0.757011,-0.333333,0.700000
2,115,0.3,-0.07,0.956,0.76,0.3,-0.075701,0.333333,0.766667
3,120,0.4,0.26,1.000,0.80,0.4,0.264954,0.666667,0.800000
4,110,0.2,-0.41,0.043,0.73,0.2,-0.416356,0.000000,0.733333
5,130,0.6,0.92,0.220,0.86,0.6,0.946264,1.333333,0.866667
6,150,1.0,2.25,1.260,1.00,1.0,2.308884,2.666667,1.000000
7,100,0.0,-1.07,-0.043,0.67,0.0,-1.097666,-0.666667,0.666667
8,105,0.1,-0.74,0.000,0.70,0.1,-0.757011,-0.333333,0.700000